<a href="https://colab.research.google.com/github/sanyasirao-surada/ML-LAB/blob/main/DWDM_EXP_2%261.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EXP-2**

In [1]:
import pandas as pd
import numpy as np

In [2]:
print("EXPERIMENT 2 : UNDERSTANDING DATA")

EXPERIMENT 2 : UNDERSTANDING DATA


In [3]:
from google.colab import files

In [4]:
uploaded = files.upload()

Saving student_data.csv to student_data.csv


In [5]:
file_name = list(uploaded.keys())[0]

In [6]:
df = pd.read_csv(file_name)

In [7]:
print("\nDataset Loaded Successfully!")


Dataset Loaded Successfully!


In [8]:
print("\nShape of Dataset:", df.shape)


Shape of Dataset: (15, 11)


In [9]:
print("\nColumn Names:\n", df.columns)


Column Names:
 Index(['StudentID', 'Name', 'Age', 'Gender', 'Major', 'Math_Score',
       'Physics_Score', 'Chemistry_Score', 'English_Score', 'CGPA',
       'Unnamed: 10'],
      dtype='object')


In [10]:
print("\nData Types:\n", df.dtypes)



Data Types:
 StudentID            int64
Name                object
Age                  int64
Gender              object
Major               object
Math_Score         float64
Physics_Score      float64
Chemistry_Score    float64
English_Score        int64
CGPA               float64
Unnamed: 10        float64
dtype: object


In [11]:
print("\nFirst 5 Records:\n", df.head())


First 5 Records:
    StudentID     Name  Age Gender Major  Math_Score  Physics_Score  \
0          1    Alice   20      F    CS        85.0           80.0   
1          2      Bob   21      M    CS        78.0           75.0   
2          3  Charlie   20      M    IT        92.0           88.0   
3          4    David   22      M    CS        88.0           85.0   
4          5      Eva   21      F    IT        76.0            NaN   

   Chemistry_Score  English_Score  CGPA  Unnamed: 10  
0             88.0             75   8.5          NaN  
1             82.0             80   7.8          NaN  
2             90.0             85   9.0          NaN  
3             86.0             78   8.6          NaN  
4             79.0             82   7.9          NaN  


In [12]:
print("\nLast 5 Records:\n", df.tail())



Last 5 Records:
     StudentID    Name  Age Gender Major  Math_Score  Physics_Score  \
10         11   Karen   24      F    IT        84.0           81.0   
11         12     Leo   21      M    CS        79.0           76.0   
12         13    Mona   22      F    IT        87.0           84.0   
13         14    Nick   20      M    CS        90.0           88.0   
14         15  Olivia   21      F    IT        83.0           80.0   

    Chemistry_Score  English_Score  CGPA  Unnamed: 10  
10             83.0             77   8.2          NaN  
11             80.0             83   7.9          NaN  
12             86.0             80   8.5          NaN  
13             89.0             85   8.8          NaN  
14             82.0             78   8.1          NaN  


In [13]:
print("\nStatistical Summary:\n", df.describe())


Statistical Summary:
        StudentID        Age  Math_Score  Physics_Score  Chemistry_Score  \
count  15.000000  15.000000   14.000000      14.000000        14.000000   
mean    8.000000  21.200000   85.642857      83.000000        85.500000   
std     4.472136   1.207122    5.637882       4.883252         4.090326   
min     1.000000  20.000000   76.000000      75.000000        79.000000   
25%     4.500000  20.000000   82.250000      80.000000        82.250000   
50%     8.000000  21.000000   86.000000      83.000000        85.500000   
75%    11.500000  22.000000   89.750000      87.500000        88.750000   
max    15.000000  24.000000   95.000000      90.000000        92.000000   

       English_Score      CGPA  Unnamed: 10  
count      15.000000  15.00000          0.0  
mean       81.400000   8.46000          NaN  
std         3.718679   0.43227          NaN  
min        75.000000   7.80000          NaN  
25%        78.500000   8.15000          NaN  
50%        81.000000   8.

In [14]:
print("\nMissing Values in Each Column:\n", df.isnull().sum())


Missing Values in Each Column:
 StudentID           0
Name                0
Age                 0
Gender              0
Major               0
Math_Score          1
Physics_Score       1
Chemistry_Score     1
English_Score       0
CGPA                0
Unnamed: 10        15
dtype: int64


In [15]:
print("\nExperiment 2 Completed Successfully")


Experiment 2 Completed Successfully


**EXP-1**

In [46]:
# Experiment 1: Matrix Operations
# Author: Student Name
# Date: DD/MM/YYYY

# Import required library
import numpy as np

In [47]:
print("="*60)

In [48]:
print("="*60)
print("EXPERIMENT 1: MATRIX OPERATIONS")
print("="*60)

EXPERIMENT 1: MATRIX OPERATIONS


In [49]:
# Step 1: Create sample matrices
print("1. Creating Matrices")
print("-"*60)

1. Creating Matrices
------------------------------------------------------------


In [50]:
print("\n1. Creating Matrices")
print("-"*60)


1. Creating Matrices
------------------------------------------------------------


In [51]:
# Matrix A (3x3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [52]:
print("Matrix A (3x3):")
print(A)


Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [54]:
print("\nMatrix B (3x3):")
print(B)


Matrix B (3x3):
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [55]:
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [57]:
print("\nMatrix C (3x2):")
print(C)


Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]


In [58]:
print("\n2. Matrix Addition (A + B)")
print("-"*60)


2. Matrix Addition (A + B)
------------------------------------------------------------


In [59]:
addition = A + B
print("Result:")
print(addition)


Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [60]:
# Step 2: Matrix Addition
print("\n\n2. Matrix Addition (A + B)")
print("-"*60)
addition = A + B
print("Result:")
print(addition)



2. Matrix Addition (A + B)
------------------------------------------------------------
Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [61]:
# Step 3: Matrix Subtraction
print("\n\n3. Matrix Subtraction (A - B)")
print("-"*60)



3. Matrix Subtraction (A - B)
------------------------------------------------------------


In [62]:
 #Step 3: Matrix Subtraction
print("\n\n3. Matrix Subtraction (A - B)")
print("-"*60)
subtraction = A - B
print("Result:")
print(subtraction)



3. Matrix Subtraction (A - B)
------------------------------------------------------------
Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [63]:
# Step 4: Matrix Multiplication
print("\n\n4. Matrix Multiplication")
print("-"*60)





4. Matrix Multiplication
------------------------------------------------------------


In [64]:
# Element-wise multiplication
element_wise = A * B
print("Element-wise Multiplication (A * B):")
print(element_wise)


Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [65]:
# Dot product (Matrix multiplication)
dot_product = np.dot(A, B)
print("\nDot Product / Matrix Multiplication (A × B):")
print(dot_product)


Dot Product / Matrix Multiplication (A × B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [66]:
 #Matrix multiplication with different sizes
mult_diff_size = np.dot(A, C)
print("\nMatrix Multiplication (A × C) - 3x3 × 3x2 = 3x2:")
print(mult_diff_size)


Matrix Multiplication (A × C) - 3x3 × 3x2 = 3x2:
[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [67]:
# Step 5: Transpose
print("\n\n5. Transpose Operation")
print("-"*60)
transpose_A = A.T
print("Transpose of Matrix A:")
print(transpose_A)

transpose_C = C.T
print("\nTranspose of Matrix C:")
print(transpose_C)



5. Transpose Operation
------------------------------------------------------------
Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of Matrix C:
[[1 3 5]
 [2 4 6]]


In [68]:
# Step 6: Determinant (only for square matrices)
print("\n\n6. Determinant Calculation")
print("-"*60)
det_A = np.linalg.det(A)
print(f"Determinant of Matrix A: {det_A:.2f}")

# Create a matrix with non-zero determinant for better example
D = np.array([[4, 3, 2],
              [1, 5, 7],
              [8, 6, 9]])
det_D = np.linalg.det(D)
print(f"Determinant of Matrix D: {det_D:.2f}")



6. Determinant Calculation
------------------------------------------------------------
Determinant of Matrix A: 0.00
Determinant of Matrix D: 85.00


In [71]:
# Step 7: Inverse (only for non-singular square matrices)
print("\n\n7. Inverse Matrix")
print("-"*60)

# Matrix A has determinant 0, so we use Matrix D
try:
    inverse_D = np.linalg.inv(D)
    print("Inverse of Matrix D:")
    print(inverse_D)

    # Verify: D × D_inverse should give Identity matrix
    verify = np.dot(D, inverse_D)
    print("\nVerification (D × D_inverse should be Identity Matrix):")
    print(np.round(verify, 2))
except:
    print("Matrix is singular and cannot be inverted")



7. Inverse Matrix
------------------------------------------------------------
Inverse of Matrix D:
[[ 0.03529412 -0.17647059  0.12941176]
 [ 0.55294118  0.23529412 -0.30588235]
 [-0.4        -0.          0.2       ]]

Verification (D × D_inverse should be Identity Matrix):
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]


In [72]:
# Step 8: Additional Operations
print("\n\n8. Additional Matrix Operations")
print("-"*60)

# Shape
print(f"Shape of Matrix A: {A.shape}")
print(f"Shape of Matrix C: {C.shape}")

# Sum of all elements
print(f"\nSum of all elements in A: {np.sum(A)}")

# Mean
print(f"Mean of Matrix A: {np.mean(A):.2f}")

# Maximum and Minimum
print(f"Maximum value in A: {np.max(A)}")
print(f"Minimum value in A: {np.min(A)}")

# Row-wise and Column-wise sum
print(f"\nRow-wise sum: {np.sum(A, axis=1)}")
print(f"Column-wise sum: {np.sum(A, axis=0)}")

print("\n" + "="*60)
print("EXPERIMENT COMPLETED SUCCESSFULLY")
print("="*60)



8. Additional Matrix Operations
------------------------------------------------------------
Shape of Matrix A: (3, 3)
Shape of Matrix C: (3, 2)

Sum of all elements in A: 45
Mean of Matrix A: 5.00
Maximum value in A: 9
Minimum value in A: 1

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]

EXPERIMENT COMPLETED SUCCESSFULLY
