<a href="https://colab.research.google.com/github/sanyasirao-surada/ML-LAB/blob/main/DWDM_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 1: Matrix Operations

In [ ]:
# Experiment 1: Matrix Operations
# Author: Student Name
# Date: DD/MM/YYYY

# Import required library
import numpy as np

print("="*60)
print("EXPERIMENT 1: MATRIX OPERATIONS")
print("="*60)

# Step 1: Create sample matrices
print("\n1. Creating Matrices")
print("-"*60)

# Matrix A (3x3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matrix B (3x3)
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix C (3x2) for different size operations
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Matrix A (3x3):")
print(A)
print("\nMatrix B (3x3):")
print(B)
print("\nMatrix C (3x2):")
print(C)

# Step 2: Matrix Addition
print("\n\n2. Matrix Addition (A + B)")
print("-"*60)
addition = A + B
print("Result:")
print(addition)

# Step 3: Matrix Subtraction
print("\n\n3. Matrix Subtraction (A - B)")
print("-"*60)
subtraction = A - B
print("Result:")
print(subtraction)

# Step 4: Matrix Multiplication
print("\n\n4. Matrix Multiplication")
print("-"*60)

# Element-wise multiplication
element_wise = A * B
print("Element-wise Multiplication (A * B):")
print(element_wise)

# Dot product (Matrix multiplication)
dot_product = np.dot(A, B)
print("\nDot Product / Matrix Multiplication (A × B):")
print(dot_product)

# Matrix multiplication with different sizes
mult_diff_size = np.dot(A, C)
print("\nMatrix Multiplication (A × C) - 3x3 × 3x2 = 3x2:")
print(mult_diff_size)

# Step 5: Transpose
print("\n\n5. Transpose Operation")
print("-"*60)
transpose_A = A.T
print("Transpose of Matrix A:")
print(transpose_A)

transpose_C = C.T
print("\nTranspose of Matrix C:")
print(transpose_C)

# Step 6: Determinant (only for square matrices)
print("\n\n6. Determinant Calculation")
print("-"*60)
det_A = np.linalg.det(A)
print(f"Determinant of Matrix A: {det_A:.2f}")

# Create a matrix with non-zero determinant for better example
D = np.array([[4, 3, 2],
              [1, 5, 7],
              [8, 6, 9]])
det_D = np.linalg.det(D)
print(f"Determinant of Matrix D: {det_D:.2f}")

# Step 7: Inverse (only for non-singular square matrices)
print("\n\n7. Inverse Matrix")
print("-"*60)

# Matrix A has determinant 0, so we use Matrix D
try:
    inverse_D = np.linalg.inv(D)
    print("Inverse of Matrix D:")
    print(inverse_D)

    # Verify: D × D_inverse should give Identity matrix
    verify = np.dot(D, inverse_D)
    print("\nVerification (D × D_inverse should be Identity Matrix):")
    print(np.round(verify, 2))
except:
    print("Matrix is singular and cannot be inverted")

# Step 8: Additional Operations
print("\n\n8. Additional Matrix Operations")
print("-"*60)

# Shape
print(f"Shape of Matrix A: {A.shape}")
print(f"Shape of Matrix C: {C.shape}")

# Sum of all elements
print(f"\nSum of all elements in A: {np.sum(A)}")

# Mean
print(f"Mean of Matrix A: {np.mean(A):.2f}")

# Maximum and Minimum
print(f"Maximum value in A: {np.max(A)}")
print(f"Minimum value in A: {np.min(A)}")

# Row-wise and Column-wise sum
print(f"\nRow-wise sum: {np.sum(A, axis=1)}")
print(f"Column-wise sum: {np.sum(A, axis=0)}")

print("\n" + "="*60)
print("EXPERIMENT COMPLETED SUCCESSFULLY")
print("="*60)

EXPERIMENT 1: MATRIX OPERATIONS

1. Creating Matrices
------------------------------------------------------------
Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B (3x3):
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]


2. Matrix Addition (A + B)
------------------------------------------------------------
Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


3. Matrix Subtraction (A - B)
------------------------------------------------------------
Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


4. Matrix Multiplication
------------------------------------------------------------
Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Dot Product / Matrix Multiplication (A × B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix Multiplication (A × C) - 3x3 × 3x2 = 3x2:
[[ 22  28]
 [ 49  64]
 [ 76 100]]


5. Transpose Operation
------------------------------------------------------------
Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpos

In [ ]:
# Experiment 2: Understanding Data
# Author: Student Name
# Date: DD/MM/YYYY

# Import required libraries
import pandas as pd
import numpy as np

print("="*80)
print("EXPERIMENT 2: UNDERSTANDING DATA")
print("="*80)

# Step 1: Create a sample dataset (Student Performance Dataset)
print("\n1. Creating Sample Dataset")
print("-"*80)

# Creating sample data
data = {
    'StudentID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace',
             'Henry', 'Ivy', 'Jack', 'Karen', 'Leo', 'Mona', 'Nick', 'Olivia'],
    'Age': [20, 21, 20, 22, 21, 23, 20, 22, 21, 20, 24, 21, 22, 20, 21],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F'],
    'Major': ['CS', 'CS', 'IT', 'CS', 'IT', 'CS', 'IT', 'CS', 'IT', 'CS',
              'IT', 'CS', 'IT', 'CS', 'IT'],
    'Math_Score': [85, 78, 92, 88, 76, 95, 82, np.nan, 89, 91, 84, 79, 87, 90, 83],
    'Physics_Score': [80, 75, 88, 85, np.nan, 90, 78, 82, 86, 89, 81, 76, 84, 88, 80],
    'Chemistry_Score': [88, 82, 90, 86, 79, 92, 85, 84, np.nan, 91, 83, 80, 86, 89, 82],
    'English_Score': [75, 80, 85, 78, 82, 88, 79, 81, 84, 86, 77, 83, 80, 85, 78],
    'CGPA': [8.5, 7.8, 9.0, 8.6, 7.9, 9.2, 8.3, 8.4, 8.7, 9.0, 8.2, 7.9, 8.5, 8.8, 8.1]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV for future use
df.to_csv('student_data.csv', index=False)
print("Sample dataset created and saved as 'student_data.csv'")

# Step 2: Load the dataset
print("\n2. Loading Dataset")
print("-"*80)
df = pd.read_csv('student_data.csv')
print("Dataset loaded successfully!")

# Step 3: Display basic information
print("\n3. Basic Dataset Information")
print("-"*80)

# Shape of dataset
print(f"Dataset Shape (Rows, Columns): {df.shape}")
print(f"Number of Records: {df.shape[0]}")
print(f"Number of Features: {df.shape[1]}")

# Column names
print(f"\nColumn Names:")
print(list(df.columns))

# Data types
print(f"\nData Types of Each Column:")
print(df.dtypes)

# Memory usage
print(f"\nMemory Usage:")
print(df.memory_usage(deep=True))

# Step 4: Display first and last rows
print("\n4. Sample Data Records")
print("-"*80)

print("First 5 rows of dataset:")
print(df.head())

print("\nLast 5 rows of dataset:")
print(df.tail())

# Random sample
print("\nRandom 3 samples:")
print(df.sample(3))

# Step 5: Statistical Summary
print("\n5. Statistical Summary of Numerical Features")
print("-"*80)
print(df.describe())

# Additional statistics
print("\nAdditional Statistics:")
print(f"Median CGPA: {df['CGPA'].median()}")
print(f"Mode of Age: {df['Age'].mode()[0]}")
print(f"Variance of Math_Score: {df['Math_Score'].var():.2f}")
print(f"Standard Deviation of Physics_Score: {df['Physics_Score'].std():.2f}")

# Step 6: Check for Missing Values
print("\n6. Missing Values Analysis")
print("-"*80)

print("Missing values count in each column:")
print(df.isnull().sum())

print("\nMissing values percentage:")
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

print(f"\nTotal missing values in dataset: {df.isnull().sum().sum()}")

# Step 7: Data Types and Unique Values
print("\n7. Column-wise Analysis")
print("-"*80)

for column in df.columns:
    print(f"\nColumn: {column}")
    print(f"  Data Type: {df[column].dtype}")
    print(f"  Unique Values: {df[column].nunique()}")
    print(f"  Non-Null Count: {df[column].count()}")

    # For categorical columns, show value counts
    if df[column].dtype == 'object' or df[column].nunique() < 10:
        print(f"  Value Distribution:")
        print(f"  {df[column].value_counts()}")

# Step 8: Numerical Columns Analysis
print("\n8. Numerical Features Analysis")
print("-"*80)

numerical_columns = df.select_dtypes(include=[np.number]).columns.tolist()
print(f"Numerical Columns: {numerical_columns}")

for col in numerical_columns:
    if col != 'StudentID':  # Skip ID column
        print(f"\n{col}:")
        print(f"  Range: {df[col].min():.2f} to {df[col].max():.2f}")
        print(f"  Mean: {df[col].mean():.2f}")
        print(f"  Median: {df[col].median():.2f}")
        print(f"  25th Percentile: {df[col].quantile(0.25):.2f}")
        print(f"  75th Percentile: {df[col].quantile(0.75):.2f}")

# Step 9: Categorical Columns Analysis
print("\n9. Categorical Features Analysis")
print("-"*80)

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
print(f"Categorical Columns: {categorical_columns}")

for col in categorical_columns:
    if col != 'Name':  # Skip name column
        print(f"\n{col} Distribution:")
        print(df[col].value_counts())
        print(f"Most Common: {df[col].mode()[0]}")

# Step 10: Additional Insights
print("\n10. Key Insights and Observations")
print("-"*80)

print("\nDataset Summary:")
print(f"• Total Students: {len(df)}")
print(f"• Age Range: {df['Age'].min()} to {df['Age'].max()} years")
print(f"• Average CGPA: {df['CGPA'].mean():.2f}")
print(f"• Highest CGPA: {df['CGPA'].max()}")
print(f"• Lowest CGPA: {df['CGPA'].min()}")

# Gender distribution
print(f"\nGender Distribution:")
print(df['Gender'].value_counts())

# Major distribution
print(f"\nMajor Distribution:")
print(df['Major'].value_counts())

# Top performers
print(f"\nTop 3 Students by CGPA:")
top_students = df.nlargest(3, 'CGPA')[['Name', 'CGPA', 'Major']]
print(top_students)

# Score averages
print(f"\nAverage Scores:")
print(f"  Math: {df['Math_Score'].mean():.2f}")
print(f"  Physics: {df['Physics_Score'].mean():.2f}")
print(f"  Chemistry: {df['Chemistry_Score'].mean():.2f}")
print(f"  English: {df['English_Score'].mean():.2f}")

print("\n" + "="*80)
print("DATA EXPLORATION COMPLETED SUCCESSFULLY")
print("="*80)

# Step 11: Save detailed report
print("\nGenerating detailed report...")
with open('data_understanding_report.txt', 'w') as f:
    f.write("="*80 + "\n")
    f.write("DATA UNDERSTANDING REPORT\n")
    f.write("="*80 + "\n\n")

    f.write("1. DATASET INFORMATION\n")
    f.write("-"*80 + "\n")
    f.write(f"Shape: {df.shape}\n")
    f.write(f"Columns: {list(df.columns)}\n\n")

    f.write("2. STATISTICAL SUMMARY\n")
    f.write("-"*80 + "\n")
    f.write(df.describe().to_string())
    f.write("\n\n")

    f.write("3. MISSING VALUES\n")
    f.write("-"*80 + "\n")
    f.write(df.isnull().sum().to_string())
    f.write("\n\n")

print("Report saved as 'data_understanding_report.txt'")

EXPERIMENT 2: UNDERSTANDING DATA

1. Creating Sample Dataset
--------------------------------------------------------------------------------
Sample dataset created and saved as 'student_data.csv'

2. Loading Dataset
--------------------------------------------------------------------------------
Dataset loaded successfully!

3. Basic Dataset Information
--------------------------------------------------------------------------------
Dataset Shape (Rows, Columns): (15, 10)
Number of Records: 15
Number of Features: 10

Column Names:
['StudentID', 'Name', 'Age', 'Gender', 'Major', 'Math_Score', 'Physics_Score', 'Chemistry_Score', 'English_Score', 'CGPA']

Data Types of Each Column:
StudentID            int64
Name                object
Age                  int64
Gender              object
Major               object
Math_Score         float64
Physics_Score      float64
Chemistry_Score    float64
English_Score        int64
CGPA               float64
dtype: object

Memory Usage:
Index       

In [ ]:
# Experiment 2: Understanding Data
# Author: Student Name
# Date: DD/MM/YYYY

# Import required libraries
import pandas as pd
import numpy as np

print("="*80)
print("EXPERIMENT 2: UNDERSTANDING DATA")
print("="*80)

# Step 1: Load the dataset
print("\n2. Loading Dataset")
print("-"*80)
df = pd.read_csv('student_data.csv')
print("Dataset loaded successfully!")
# Create DataFrame
df = pd.DataFrame(data)

# # Step 2:Save to CSV for future use
df.to_csv('student_data.csv', index=False)
print("Sample dataset created and saved as 'student_data.csv'")

# Step 3: Display basic information
print("\n3. Basic Dataset Information")
print("-"*80)

# Shape of dataset
print(f"Dataset Shape (Rows, Columns): {df.shape}")
print(f"Number of Records: {df.shape[0]}")
print(f"Number of Features: {df.shape[1]}")

# Column names
print(f"\nColumn Names:")
print(list(df.columns))

# Data types
print(f"\nData Types of Each Column:")
print(df.dtypes)

# Memory usage
print(f"\nMemory Usage:")
print(df.memory_usage(deep=True))

# Step 4: Display first and last rows
print("\n4. Sample Data Records")
print("-"*80)

print("First 5 rows of dataset:")
print(df.head())

print("\nLast 5 rows of dataset:")
print(df.tail())

# Random sample
print("\nRandom 3 samples:")
print(df.sample(3))

# Step 5: Statistical Summary
print("\n5. Statistical Summary of Numerical Features")
print("-"*80)
print(df.describe())

# Additional statistics
print("\nAdditional Statistics:")
print(f"Median CGPA: {df['CGPA'].median()}")
print(f"Mode of Age: {df['Age'].mode()[0]}")
print(f"Variance of Math_Score: {df['Math_Score'].var():.2f}")
print(f"Standard Deviation of Physics_Score: {df['Physics_Score'].std():.2f}")

# Step 6: Check for Missing Values
print("\n6. Missing Values Analysis")
print("-"*80)

print("Missing values count in each column:")
print(df.isnull().sum())

print("\nMissing values percentage:")
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

print(f"\nTotal missing values in dataset: {df.isnull().sum().sum()}")

# Step 7: Data Types and Unique Values
print("\n7. Column-wise Analysis")
print("-"*80)

for column in df.columns:
    print(f"\nColumn: {column}")
    print(f"  Data Type: {df[column].dtype}")
    print(f"  Unique Values: {df[column].nunique()}")
    print(f"  Non-Null Count: {df[column].count()}")

    # For categorical columns, show value counts
    if df[column].dtype == 'object' or df[column].nunique() < 10:
        print(f"  Value Distribution:")
        print(f"  {df[column].value_counts()}")

# Step 8: Numerical Columns Analysis
print("\n8. Numerical Features Analysis")
print("-"*80)

numerical_columns = df.select_dtypes(include=[np.number]).columns.tolist()
print(f"Numerical Columns: {numerical_columns}")

for col in numerical_columns:
    if col != 'StudentID':  # Skip ID column
        print(f"\n{col}:")
        print(f"  Range: {df[col].min():.2f} to {df[col].max():.2f}")
        print(f"  Mean: {df[col].mean():.2f}")
        print(f"  Median: {df[col].median():.2f}")
        print(f"  25th Percentile: {df[col].quantile(0.25):.2f}")
        print(f"  75th Percentile: {df[col].quantile(0.75):.2f}")

# Step 9: Categorical Columns Analysis
print("\n9. Categorical Features Analysis")
print("-"*80)

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
print(f"Categorical Columns: {categorical_columns}")

for col in categorical_columns:
    if col != 'Name':  # Skip name column
        print(f"\n{col} Distribution:")
        print(df[col].value_counts())
        print(f"Most Common: {df[col].mode()[0]}")

# Step 10: Additional Insights
print("\n10. Key Insights and Observations")
print("-"*80)

print("\nDataset Summary:")
print(f"• Total Students: {len(df)}")
print(f"• Age Range: {df['Age'].min()} to {df['Age'].max()} years")
print(f"• Average CGPA: {df['CGPA'].mean():.2f}")
print(f"• Highest CGPA: {df['CGPA'].max()}")
print(f"• Lowest CGPA: {df['CGPA'].min()}")

# Gender distribution
print(f"\nGender Distribution:")
print(df['Gender'].value_counts())

# Major distribution
print(f"\nMajor Distribution:")
print(df['Major'].value_counts())

# Top performers
print(f"\nTop 3 Students by CGPA:")
top_students = df.nlargest(3, 'CGPA')[['Name', 'CGPA', 'Major']]
print(top_students)

# Score averages
print(f"\nAverage Scores:")
print(f"  Math: {df['Math_Score'].mean():.2f}")
print(f"  Physics: {df['Physics_Score'].mean():.2f}")
print(f"  Chemistry: {df['Chemistry_Score'].mean():.2f}")
print(f"  English: {df['English_Score'].mean():.2f}")

print("\n" + "="*80)
print("DATA EXPLORATION COMPLETED SUCCESSFULLY")
print("="*80)

# Step 11: Save detailed report
print("\nGenerating detailed report...")
with open('data_understanding_report.txt', 'w') as f:
    f.write("="*80 + "\n")
    f.write("DATA UNDERSTANDING REPORT\n")
    f.write("="*80 + "\n\n")

    f.write("1. DATASET INFORMATION\n")
    f.write("-"*80 + "\n")
    f.write(f"Shape: {df.shape}\n")
    f.write(f"Columns: {list(df.columns)}\n\n")

    f.write("2. STATISTICAL SUMMARY\n")
    f.write("-"*80 + "\n")
    f.write(df.describe().to_string())
    f.write("\n\n")

    f.write("3. MISSING VALUES\n")
    f.write("-"*80 + "\n")
    f.write(df.isnull().sum().to_string())
    f.write("\n\n")

print("Report saved as 'data_understanding_report.txt'")

EXPERIMENT 2: UNDERSTANDING DATA

2. Loading Dataset
--------------------------------------------------------------------------------
Dataset loaded successfully!
Sample dataset created and saved as 'student_data.csv'

3. Basic Dataset Information
--------------------------------------------------------------------------------
Dataset Shape (Rows, Columns): (15, 10)
Number of Records: 15
Number of Features: 10

Column Names:
['StudentID', 'Name', 'Age', 'Gender', 'Major', 'Math_Score', 'Physics_Score', 'Chemistry_Score', 'English_Score', 'CGPA']

Data Types of Each Column:
StudentID            int64
Name                object
Age                  int64
Gender              object
Major               object
Math_Score         float64
Physics_Score      float64
Chemistry_Score    float64
English_Score        int64
CGPA               float64
dtype: object

Memory Usage:
Index              132
StudentID          120
Name               802
Age                120
Gender             750
Major 